Repository GeorgeShao/PowerSearch, pull requests merged in 2020-10, with the labels that each got.

#19 Implement multithreading to speed up processes
  powersearch.py
Labels: enhancement

#24 Migrate settings from global variables to settings.toml file
  powersearch.py
Labels: bug

#27 Settings toml cli option
  powersearch.py
Labels: enhancement, good first issue

#28 Add file searching completion time logging
  powersearch.py
Labels: enhancement, good first issue

#32 Add contributing.md
  CONTRIBUTING.md
Labels: documentation

#33 Updated documentation file
  Powersearch.JPG
  README.md
Labels: documentation

#37 Improve args docs filepath
  README.md
  powersearch.py
Labels: documentation, enhancement
